version: "3.9"

services:
  waf:
    image: owasp/modsecurity-crs:3-nginx
    ports:
      - "80:80"
    depends_on:
      - web
    environment:
      - PROXY=1
      - PARANOIA=1
      - BACKEND=http://web:8000
      - ALLOWED_METHODS=GET HEAD POST OPTIONS DELETE PUT
    restart: on-failure
  web:
    build: .
    platform: linux/amd64
    command: bash -c "gunicorn config.wsgi:application --bind 0.0.0.0:8000 --worker-tmp-dir /dev/shm --workers=2 --threads=4 --worker-class=gthread"
    volumes:
      - .:/web-gateway:rw
    image:
      web-gateway-app
    expose:
      - "8000"
    env_file:
      - ./.env
    restart: on-failure
