# Generated by Django 3.2.6 on 2021-09-10 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='site_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.siteowner'),
        ),
    ]
